### PR TITLE
Added easing functions demo

### PR DESCRIPTION
**Pull request by mikatuo**
I wanted to see all easing functions in action and created a demo collection. Is it something that worth putting into the examples project? Or maybe somewhere else?

If yes:
Please let me know if you have any suggestions. Is it necessary to optimize it, how? I can reduce image sizes by 20-40px.
Any ideas how to name it? It's "Easing functions (tweens)" right now.

Demo:
dmengine_2TTy81ootX

Changes:
- added easing.collection
- added easing.atlas (2048 x 1024)

image

image

### CODE REVIEW

**Comment by britzl** [comment]
@mikatuo I've missed this PR. I'm terribly sorry! Would you still like to see it merged?

**Comment by Jhonnyg** [comment]
I missed this as well, I think it looks like a great addition!

**Comment by mikatuo** [comment]
Sure. Thank you)

**Comment by britzl** [comment]
Looks good! Thank you!

**Pull request merged**
