### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by aglitchman**
Fixes https://github.com/defold/examples/issues/59

### CODE REVIEW

**Comment by aglitchman** [comment]
In the templates, they assign the following labels:
- `example`
- `feature request`
- `bug`

Is it ok? Because there are no `example` and `feature request` labels in the issues and I'm not sure if it's fine to set those new labels in templates.

**Review by britzl — APPROVED** [review]
Excellent! Thanks!

**Comment by aglitchman** [comment]
> Excellent! Thanks!

You still need to add the new labels in the project settings! `example` and `feature request`.

**Comment by britzl** [comment]
> You still need to add the new labels in the project settings! `example` and `feature request`.

Added them!

**Pull request merged**
