### PR TITLE
New example: particlefx "confetti"

### PR DESCRIPTION
**Pull request by aglitchman**
In the example, particlefx is used to create a confetti fireworks effect. It is usually used on final screens to congratulate the player on successful completion of a level or game.

Plus,  I increased the limit on emitters in `game.project` so that in this example, visitors of the examples site can launch confetti as many times as they want for their own pleasure 😄

https://github.com/user-attachments/assets/a826e56e-c18c-47c2-9f9e-570abe53eb2a

### CODE REVIEW

**Review by AGulev — APPROVED** [review]
Great! Thank you!!

**Comment by AGulev** [comment]
hmm, for some reason it doesn't work :

```
ERROR:SCRIPT: examples/_main/loader.script:13: attempt to index local 'example' (a nil value)
stack traceback:
  examples/_main/loader.script:13: in function <examples/_main/loader.script:3>
  ```
  
  https://defold.com/examples/particles/confetti/

**Comment by aglitchman** [comment]
It runs well:

image

Cache issue? Examples website needs some kind of cache-busting, for example to build the game in the different folder every time.

**Comment by AGulev** [comment]
ah, now it works for me as well
never mind

**Pull request merged**
